/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JOptionPane;
import static residencial.Login.clientes;

/**
 *
 * @author Laboratorios
 */
public class AgregarCliente extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xA = this.getX();
    int yA = this.getY();

    public AgregarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jGeneros = new javax.swing.ButtonGroup();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        mover = new javax.swing.JButton();
        ColorBarra = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jApellidos = new javax.swing.JTextField();
        jCedula = new javax.swing.JTextField();
        jEdad = new javax.swing.JComboBox<>();
        jFamilia = new javax.swing.JComboBox<>();
        jMasculino = new javax.swing.JRadioButton();
        jFamenino = new javax.swing.JRadioButton();
        labelFamilia = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        labelMonto = new javax.swing.JLabel();
        jSector = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        iconoRe = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jGeneros.add(this.jFamenino);
        jGeneros.add(this.jMasculino);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(450, 200, 50, 50));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setBackground(new java.awt.Color(46, 51, 58));
        minimizar.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("-");
        minimizar.setBorder(null);
        minimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizarMouseMoved(evt);
            }
        });
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 0, 60, 24));

        cerrar.setBackground(new java.awt.Color(46, 51, 58));
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.setBorder(null);
        cerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cerrarMouseMoved(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 0, 60, 24));

        mover.setBackground(new java.awt.Color(46, 51, 58));
        mover.setBorderPainted(false);
        mover.setContentAreaFilled(false);
        mover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moverMouseMoved(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        getContentPane().add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 492, 24));

        ColorBarra.setBackground(new java.awt.Color(46, 51, 58));
        ColorBarra.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ColorBarra.setForeground(new java.awt.Color(204, 0, 0));
        ColorBarra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorBarra.setText("Agregar Cliente");
        ColorBarra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ColorBarra.setOpaque(true);
        ColorBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ColorBarraMouseMoved(evt);
            }
        });
        getContentPane().add(ColorBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 24));

        jNombre.setBackground(new java.awt.Color(113, 117, 111));
        jNombre.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jNombre.setForeground(new java.awt.Color(255, 255, 255));
        jNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 2, true));
        jNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNombreMouseClicked(evt);
            }
        });
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 48, 180, 24));

        jApellidos.setBackground(new java.awt.Color(113, 117, 111));
        jApellidos.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jApellidos.setForeground(new java.awt.Color(255, 255, 255));
        jApellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 2, true));
        jApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jApellidosMouseClicked(evt);
            }
        });
        getContentPane().add(jApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 96, 180, 24));

        jCedula.setBackground(new java.awt.Color(113, 117, 111));
        jCedula.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jCedula.setForeground(new java.awt.Color(255, 255, 255));
        jCedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 2, true));
        jCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCedulaMouseClicked(evt);
            }
        });
        getContentPane().add(jCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 144, 180, 24));

        jEdad.setBackground(new java.awt.Color(113, 117, 111));
        jEdad.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jEdad.setSelectedItem(0);
        jEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        getContentPane().add(jEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 192, 48, 24));

        jFamilia.setBackground(new java.awt.Color(113, 117, 111));
        jFamilia.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jFamilia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jFamilia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        getContentPane().add(jFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 192, -1, 24));

        jMasculino.setBackground(new java.awt.Color(113, 117, 111));
        jGeneros.add(jMasculino);
        jMasculino.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jMasculino.setText("Masculino");
        jMasculino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        jMasculino.setBorderPainted(true);
        getContentPane().add(jMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 240, 96, 24));

        jFamenino.setBackground(new java.awt.Color(113, 117, 111));
        jGeneros.add(jFamenino);
        jFamenino.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        jFamenino.setMnemonic(1);
        jFamenino.setSelected(true);
        jFamenino.setText("Femenino");
        jFamenino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        jFamenino.setBorderPainted(true);
        getContentPane().add(jFamenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 264, 96, -1));

        labelFamilia.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelFamilia.setForeground(new java.awt.Color(153, 0, 0));
        labelFamilia.setText("Familia");
        getContentPane().add(labelFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 192, 60, 24));

        labelNombre.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(153, 0, 0));
        labelNombre.setText("Nombre");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 48, 84, 24));

        labelApellidos.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelApellidos.setForeground(new java.awt.Color(153, 0, 0));
        labelApellidos.setText("Apellidos");
        getContentPane().add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 96, 84, 24));

        labelCedula.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(153, 0, 0));
        labelCedula.setText("Cedula");
        getContentPane().add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 144, 72, 24));

        labelEdad.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelEdad.setForeground(new java.awt.Color(153, 0, 0));
        labelEdad.setText("Edad");
        getContentPane().add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 192, 36, 24));

        labelGenero.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(153, 0, 0));
        labelGenero.setText("Genero");
        getContentPane().add(labelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 252, 48, 24));

        agregar.setBackground(new java.awt.Color(107, 25, 25));
        agregar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 360, -1, -1));

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eraser.png"))); // NOI18N
        limpiar.setBorderPainted(false);
        limpiar.setContentAreaFilled(false);
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarMouseClicked(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 348, 48, 36));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow.png"))); // NOI18N
        regresar.setBorderPainted(false);
        regresar.setContentAreaFilled(false);
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 348, 48, 36));

        labelMonto.setFont(new java.awt.Font("Candara", 1, 15)); // NOI18N
        labelMonto.setForeground(new java.awt.Color(153, 0, 0));
        labelMonto.setText("lugar de habitacion");
        getContentPane().add(labelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 132, 36));

        jSector.setBackground(new java.awt.Color(113, 117, 111));
        jSector.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jSector.setForeground(new java.awt.Color(255, 255, 255));
        jSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sector A", "Sector B", "Sector C" }));
        jSector.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 1, true));
        getContentPane().add(jSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 312, 156, 24));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        iconoRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sol4.png"))); // NOI18N
        jPanel1.add(iconoRe);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 120, 108));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red-and-white-bars-hd-wallpaper-7530.jpg"))); // NOI18N
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 51, 58), 3, true));
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoMouseMoved(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
        minimizar.setBackground(new Color(0, 102, 102));

    }//GEN-LAST:event_minimizarMouseClicked

    private void moverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseClicked
        mover.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseClicked

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed

    }//GEN-LAST:event_moverMousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        int x = (punto.x - xA);
        int y = (punto.y - yA - 10);
        this.setLocation(x, y);
    }//GEN-LAST:event_moverMouseDragged

    private void cerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseMoved
        cerrar.setBackground(Color.red);
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_cerrarMouseMoved

    private void minimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseMoved
        minimizar.setBackground(new Color(32, 178, 170));
        cerrar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_minimizarMouseMoved

    private void moverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseEntered
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseEntered

    private void moverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseExited
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseExited

    private void ColorBarraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorBarraMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_ColorBarraMouseMoved

    private void moverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
        cerrar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseMoved

    private void fondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseMoved
        cerrar.setBackground(new Color(46, 51, 58));
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_fondoMouseMoved

    private void jNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNombreMouseClicked
    }//GEN-LAST:event_jNombreMouseClicked

    private void jApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jApellidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jApellidosMouseClicked

    private void jCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCedulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCedulaMouseClicked

    private void limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarMouseClicked
        jNombre.setText("");
        jApellidos.setText("");
        jCedula.setText("");
        jEdad.setSelectedIndex(0);
        jFamenino.setSelected(false);
        jMasculino.setSelected(false);
        jFamilia.setSelectedIndex(0);
    }//GEN-LAST:event_limpiarMouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        jNombre.setBackground(new Color(113,117,111));
        jApellidos.setBackground(new Color(113,117,111));
        jCedula.setBackground(new Color(113,117,111));
        int cont=0;
        try {
            int monto;
            String genero = "";
            boolean fam = false;
            boolean comprueba = true;
            boolean comprueba2=true;
            for (Cliente cliente : Login.clientes) {
                if (cliente.id == Integer.parseInt(jCedula.getText())) {
                    comprueba = false;
                    JOptionPane.showMessageDialog(null,"El cliente " + cliente.nombre + " ya existe");
                }
            } if (jNombre.getText().isEmpty()) {//validacion de que el campo del nombre no este vacio
                jNombre.setBackground(new Color(150,50,100));//ahi esta el color rojo
                JOptionPane.showMessageDialog(null, "Verificar los campos rojos");
                cont++;
                comprueba2 = false;
            } if (jCedula.getText().isEmpty()) {//validacion de que el campo del nombre no este vacio
                jCedula.setBackground(new Color(150,50,100));//ahi esta el color rojo
                if (cont==0) {
                JOptionPane.showMessageDialog(null, "Verificar los campos rojos");
                }
                comprueba2 = false;
                
            } if (jApellidos.getText().isEmpty()) {//validacion de que el campo del nombre no este vacio
                jApellidos.setBackground(new Color(150,50,100));//ahi esta el color rojo
                if (cont==0) {
                JOptionPane.showMessageDialog(null, "Verificar los campos rojos");
                }
                comprueba2 = false;
            } 
            if (comprueba && comprueba2) {

                try {
                    switch (jSector.getSelectedIndex()) {
                        case 0:
                            monto = 1000000;
                            if (Sector.contadorSectorA < 11) {
                                switch (jFamilia.getSelectedIndex()) {
                                    case 0:
                                        fam = true;
                                        break;
                                    case 1:
                                        fam = false;
                                        break;
                                }
                                switch (jGeneros.getSelection().getMnemonic()) {
                                    case 0:
                                        genero = "Masculino";
                                        break;
                                    case 1:
                                        genero = "Femenino";
                                        break;
                                }
                                Login.clientes.add(new Cliente(monto, fam, Integer.parseInt(jCedula.getText()), jNombre.getText(),
                                        jApellidos.getText(), genero, (jEdad.getSelectedIndex() + 18)));
                                JOptionPane.showMessageDialog(null, "El cliente " + jNombre.getText() + " fue agregado exitosamente!");
                            
                            } else {
                                JOptionPane.showMessageDialog(null, "El sector A esta lleno");
                            }
                            break;
                        case 1:
                            monto = 750000;

                            if (Sector.contadorSectorB < 11) {
                                switch (jFamilia.getSelectedIndex()) {
                                    case 0:
                                        fam = true;
                                        break;
                                    case 1:
                                        fam = false;
                                        break;
                                }
                                switch (jGeneros.getSelection().getMnemonic()) {
                                    case 0:
                                        genero = "Masculino";
                                        break;
                                    case 1:
                                        genero = "Femenino";
                                        break;
                                }
                                Login.clientes.add(new Cliente(monto, fam, Integer.parseInt(jCedula.getText()), jNombre.getText(),
                                        jApellidos.getText(), genero, (jEdad.getSelectedIndex() + 18)));
                                JOptionPane.showMessageDialog(null, "El cliente " + jNombre.getText() + " fue agregado exitosamente!");
                            } else {
                                JOptionPane.showMessageDialog(null, "El sector B esta lleno");
                            }
                            break;
                        case 2:
                            monto = 550000;
                            if (Sector.contadorSectorC < 11) {
                                switch (jFamilia.getSelectedIndex()) {
                                    case 0:
                                        fam = true;
                                        break;
                                    case 1:
                                        fam = false;
                                        break;
                                }
                                switch (jGeneros.getSelection().getMnemonic()) {
                                    case 0:
                                        genero = "Masculino";
                                        break;
                                    case 1:
                                        genero = "Femenino";
                                        break;
                                }
                                Login.clientes.add(new Cliente(monto, fam, Integer.parseInt(jCedula.getText()), jNombre.getText(),
                                        jApellidos.getText(), genero, (jEdad.getSelectedIndex() + 18)));
                                JOptionPane.showMessageDialog(null, "El cliente " + jNombre.getText() + " fue agregado exitosamente!");
                                
                            } else {
                                JOptionPane.showMessageDialog(null, "El sector C esta lleno");
                            }
                            break;

                    }
                } catch (NumberFormatException | HeadlessException ex) {
                    JOptionPane.showMessageDialog(null, "Ingresaste un dato mal, favor verifica que \nestes ingresando los datos bien");
                }
                }
        } catch (NumberFormatException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Ingresaste mal un dato, intenta de nuevo por favor!");
        }
    }//GEN-LAST:event_agregarMouseClicked

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        this.dispose();
        ControlClientes ventana = new ControlClientes();
        ventana.setVisible(true);
    }//GEN-LAST:event_regresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorBarra;
    private javax.swing.JButton agregar;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoRe;
    private javax.swing.JTextField jApellidos;
    private javax.swing.JTextField jCedula;
    private javax.swing.JComboBox<String> jEdad;
    private javax.swing.JRadioButton jFamenino;
    private javax.swing.JComboBox<String> jFamilia;
    private javax.swing.ButtonGroup jGeneros;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jMasculino;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jSector;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelFamilia;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton mover;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
