/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Laboratorios
 */
public class ControlClientes extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xA= this.getX();
    int yA = this.getY();

    
    public ControlClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        Date date = new Date();
        int dia=date.getDay();
        String nombreDia;
        if (dia==0) {nombreDia="Domingo";} else if(dia==1){nombreDia="Lunes";}
        else if(dia==2){nombreDia="Martes";}else if(dia==3){nombreDia="Miercoles";}
        else if(dia==4){nombreDia="Jueves";}else if(dia==5){nombreDia="Viernes";}else{nombreDia="Sabado";}
        String texto=nombreDia;
        texto = texto + "  "+String.valueOf(date.getDate())+" / " + String.valueOf(date.getMonth()+1) + " / " 
                + String.valueOf((1900+date.getYear())) ;
        fecha.setText(texto);
            Hora h = new Hora(hora);
        h.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        mover = new javax.swing.JButton();
        ColorBarra = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        mantenimiento = new javax.swing.JButton();
        mantenimientoL = new javax.swing.JButton();
        controlUsuarios = new javax.swing.JButton();
        contolUsuariosL = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconoRe = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(450, 200, 50, 50));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setBackground(new java.awt.Color(46, 51, 58));
        minimizar.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("-");
        minimizar.setBorder(null);
        minimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizarMouseMoved(evt);
            }
        });
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 0, 60, 24));

        cerrar.setBackground(new java.awt.Color(46, 51, 58));
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.setBorder(null);
        cerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cerrarMouseMoved(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 0, 60, 24));

        mover.setBackground(new java.awt.Color(46, 51, 58));
        mover.setBorderPainted(false);
        mover.setContentAreaFilled(false);
        mover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moverMouseMoved(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        getContentPane().add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 492, 24));

        ColorBarra.setBackground(new java.awt.Color(46, 51, 58));
        ColorBarra.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ColorBarra.setForeground(new java.awt.Color(204, 0, 0));
        ColorBarra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorBarra.setText("Control de Clientes");
        ColorBarra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ColorBarra.setOpaque(true);
        ColorBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ColorBarraMouseMoved(evt);
            }
        });
        getContentPane().add(ColorBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 24));

        fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(102, 0, 0));
        fecha.setText("fecha");
        fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)), "fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 168, 36));

        hora.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        hora.setForeground(new java.awt.Color(153, 0, 0));
        hora.setText("hora");
        hora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)), "hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 168, 48));

        mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/create-group-button.png"))); // NOI18N
        mantenimiento.setBorderPainted(false);
        mantenimiento.setContentAreaFilled(false);
        mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mantenimientoMouseClicked(evt);
            }
        });
        getContentPane().add(mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 216, 144, 84));

        mantenimientoL.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        mantenimientoL.setForeground(new java.awt.Color(51, 0, 0));
        mantenimientoL.setText("Agregar cliente");
        mantenimientoL.setBorderPainted(false);
        mantenimientoL.setContentAreaFilled(false);
        mantenimientoL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mantenimientoL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(mantenimientoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 276, 132, 24));

        controlUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes-clientes-contactos-usercard-icono-5311-48.png"))); // NOI18N
        controlUsuarios.setBorderPainted(false);
        controlUsuarios.setContentAreaFilled(false);
        controlUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                controlUsuariosMouseMoved(evt);
            }
        });
        controlUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controlUsuariosMouseClicked(evt);
            }
        });
        getContentPane().add(controlUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 84, 144, 108));

        contolUsuariosL.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        contolUsuariosL.setForeground(new java.awt.Color(51, 0, 0));
        contolUsuariosL.setText("Clientes");
        contolUsuariosL.setBorderPainted(false);
        contolUsuariosL.setContentAreaFilled(false);
        contolUsuariosL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contolUsuariosL.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(contolUsuariosL, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 168, 84, -1));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow.png"))); // NOI18N
        regresar.setBorderPainted(false);
        regresar.setContentAreaFilled(false);
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 24, 60, 36));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar usuario.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 96, 108, 96));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Modificar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 108, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        iconoRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sol4.png"))); // NOI18N
        jPanel1.add(iconoRe);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 120, 108));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red-and-white-bars-hd-wallpaper-7530.jpg"))); // NOI18N
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 51, 58), 3, true));
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoMouseMoved(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 468));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
        minimizar.setBackground(new Color(0,102,102));
        
    }//GEN-LAST:event_minimizarMouseClicked

    private void moverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseClicked
        mover.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseClicked

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed

    }//GEN-LAST:event_moverMousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        Point punto=MouseInfo.getPointerInfo().getLocation();
        int x=(punto.x-xA);
        int y=(punto.y-yA-10);
        this.setLocation(x, y);
    }//GEN-LAST:event_moverMouseDragged

    private void cerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseMoved
    cerrar.setBackground(Color.red);
    minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_cerrarMouseMoved

    private void minimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseMoved
        minimizar.setBackground(new Color(32, 178, 170));
        cerrar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_minimizarMouseMoved

    private void moverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseEntered
        mover.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_moverMouseEntered

    private void moverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseExited
        mover.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_moverMouseExited

    private void ColorBarraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorBarraMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_ColorBarraMouseMoved

    private void moverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseMoved

    private void fondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseMoved
        cerrar.setBackground(new Color(46, 51, 58));
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_fondoMouseMoved

    private void controlUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlUsuariosMouseMoved
    }//GEN-LAST:event_controlUsuariosMouseMoved

    private void controlUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlUsuariosMouseClicked
        this.dispose();
        SeleccionDeSector ventana = new SeleccionDeSector();
        ventana.show();
    }//GEN-LAST:event_controlUsuariosMouseClicked

    private void mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mantenimientoMouseClicked
        this.dispose();
        AgregarCliente ventana = new AgregarCliente();
        ventana.show();
    }//GEN-LAST:event_mantenimientoMouseClicked

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        this.dispose();
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_regresarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
        ModificarUsuario ventana = new ModificarUsuario();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorBarra;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton contolUsuariosL;
    private javax.swing.JButton controlUsuarios;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel iconoRe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mantenimiento;
    private javax.swing.JButton mantenimientoL;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton mover;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
