/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author Farat
 */
public class Empleados extends javax.swing.JFrame {

   

    /**
     * Creates new form Miscellania
     */
    public Empleados() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_conserge = new javax.swing.JButton();
        btn_guarda = new javax.swing.JButton();
        btn_admi = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_conserge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/human-resources (1).png"))); // NOI18N
        btn_conserge.setContentAreaFilled(false);
        btn_conserge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consergeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_conserge, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 100, -1));

        btn_guarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/policeman.png"))); // NOI18N
        btn_guarda.setContentAreaFilled(false);
        btn_guarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 100, -1));

        btn_admi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon (1).png"))); // NOI18N
        btn_admi.setContentAreaFilled(false);
        btn_admi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow - copia.png"))); // NOI18N
        btn_atras.setContentAreaFilled(false);
        btn_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_atrasMouseClicked(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sol4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 190, 130));

        hora.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        hora.setForeground(new java.awt.Color(153, 0, 0));
        hora.setText("hora");
        hora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)), "hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 168, 48));

        fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(102, 0, 0));
        fecha.setText("fecha");
        fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)), "fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 168, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Administrador");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Vigilancia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Conserje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red-and-white-bars-hd-wallpaper-7530.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -1, 650, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consergeActionPerformed
        
        
         Conserje informacion = new Conserje();
       informacion.show();
       this.dispose();
        
        
    }//GEN-LAST:event_btn_consergeActionPerformed

    private void btn_guardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardaActionPerformed
        
       Vigilancia informacion = new Vigilancia();
       informacion.show();
       this.dispose();
        
        
    }//GEN-LAST:event_btn_guardaActionPerformed

    private void btn_admiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admiActionPerformed
        
        
       Administrador informacion = new Administrador();
       informacion.show();
       this.dispose();
        
        
    }//GEN-LAST:event_btn_admiActionPerformed

    private void btn_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_atrasMouseClicked
        this.dispose();
        MenuMiscelanea ventana = new MenuMiscelanea();
        ventana.show();
    }//GEN-LAST:event_btn_atrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admi;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_conserge;
    private javax.swing.JButton btn_guarda;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
