/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

import java.util.Date;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorios
 */
public class Login extends javax.swing.JFrame {

    int xA = this.getX();
    int yA = this.getY();

    public static ArrayList<Cliente> clientes = new ArrayList<Cliente>();

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);

        Date date = new Date();
        int dia = date.getDay();
        String nombreDia;
        if (dia == 0) {        nombreDia = "Domingo";
        } else if (dia == 1) { nombreDia = "Lunes";
        } else if (dia == 2) { nombreDia = "Martes";
        } else if (dia == 3) { nombreDia = "Miercoles";
        } else if (dia == 4) { nombreDia = "Jueves";
        } else if (dia == 5) { nombreDia = "Viernes";  } else {nombreDia = "Sabado";
        }
        String texto = nombreDia;
        texto = texto + "  " + String.valueOf(date.getDate()) + " / " + String.valueOf(date.getMonth() + 1) + " / "
                + String.valueOf((1900 + date.getYear()));
        fecha.setText(texto);
        Hora h = new Hora(hora);
        h.start();
        try {
            BufferedReader br = new BufferedReader(new FileReader("./clientes.txt"));
            String line = br.readLine();
            int id;
            String nombre;
            String apellidos;
            String genero;
            int edad;
            int monto;
            boolean familia;
            while (line != null) {
                id = Integer.parseInt(line);
                line = br.readLine();
                nombre = line;
                line = br.readLine();
                
                apellidos = line;
                line = br.readLine();
                genero = line;
                line = br.readLine();
                edad = Integer.parseInt(line);
                line = br.readLine();
                monto = Integer.parseInt(line);
                line = br.readLine();
                if (Integer.parseInt(line) == 1) {
                    familia = true;
                } else {
                    familia = false;
                }
                switch (monto) {
                    case 1000000:
                        Sector.contadorSectorA++;
                        clientes.add(new Cliente(monto, familia, id, nombre, apellidos, genero, edad));
                        break;
                    case 750000:
                        Sector.contadorSectorB++;
                        clientes.add(new Cliente(monto, familia, id, nombre, apellidos, genero, edad));
                        break;
                    case 550000:
                        Sector.contadorSectorC++;
                        clientes.add(new Cliente(monto, familia, id, nombre, apellidos, genero, edad));
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Un cliente fue mal registrado debido a que tenia un monto equivocado");
                        break;
                }

                line = br.readLine();
            }
        } catch (IOException | NumberFormatException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Hubo un error en la lectura de los clientes");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        contra = new javax.swing.JLabel();
        jusuario = new javax.swing.JTextField();
        jcontrasena = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        mover = new javax.swing.JButton();
        ColorBarra = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconoRe = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(450, 200, 50, 50));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Texto.setForeground(new java.awt.Color(204, 5, 5));
        Texto.setText("Usuario");
        getContentPane().add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 108, 108, 24));

        contra.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        contra.setForeground(new java.awt.Color(204, 5, 5));
        contra.setText("Contraseña");
        getContentPane().add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 156, 156, -1));

        jusuario.setBackground(new java.awt.Color(102, 102, 102));
        jusuario.setForeground(new java.awt.Color(255, 255, 255));
        jusuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jusuario.setBorder(new javax.swing.border.MatteBorder(null));
        jusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 108, 120, 24));

        jcontrasena.setBackground(new java.awt.Color(102, 102, 102));
        jcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        jcontrasena.setBorder(new javax.swing.border.MatteBorder(null));
        jcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontrasenaActionPerformed(evt);
            }
        });
        jcontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcontrasenaKeyPressed(evt);
            }
        });
        getContentPane().add(jcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 168, 120, 24));

        ingresar.setBackground(new java.awt.Color(102, 0, 0));
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("Ingresar");
        ingresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ingresarMouseMoved(evt);
            }
        });
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 252, 72, -1));

        minimizar.setBackground(new java.awt.Color(46, 51, 58));
        minimizar.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("-");
        minimizar.setBorder(null);
        minimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizarMouseMoved(evt);
            }
        });
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 60, 24));

        cerrar.setBackground(new java.awt.Color(46, 51, 58));
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.setBorder(null);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cerrarMouseMoved(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, 24));

        mover.setBackground(new java.awt.Color(46, 51, 58));
        mover.setBorderPainted(false);
        mover.setContentAreaFilled(false);
        mover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moverMouseMoved(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        getContentPane().add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 24));

        ColorBarra.setBackground(new java.awt.Color(46, 51, 58));
        ColorBarra.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ColorBarra.setForeground(new java.awt.Color(204, 0, 0));
        ColorBarra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorBarra.setText(" Login");
        ColorBarra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ColorBarra.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ColorBarra.setOpaque(true);
        ColorBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ColorBarraMouseMoved(evt);
            }
        });
        getContentPane().add(ColorBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 516, 24));

        hora.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        hora.setForeground(new java.awt.Color(153, 0, 0));
        hora.setText("hora");
        hora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)), "hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 372, 168, 48));

        fecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(102, 0, 0));
        fecha.setText("fecha");
        fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)), "fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 168, 36));

        jLabel1.setText("admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 132, 36, -1));

        jLabel2.setText("123456");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        iconoRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sol4.png"))); // NOI18N
        jPanel1.add(iconoRe);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 120, 108));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red-and-white-bars-hd-wallpaper-7530.jpg"))); // NOI18N
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 51, 58), 3, true));
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoMouseMoved(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 468));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusuarioActionPerformed

    private void jcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcontrasenaActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        //this.dispose(); no utilizo el dispose para que termine losnhilos activos
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
        minimizar.setBackground(new Color(0, 102, 102));

    }//GEN-LAST:event_minimizarMouseClicked

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        String usuario = "admin";
        String contrasena = "123456";
        String usuarioA = jusuario.getText();
        String contrasenaA = jcontrasena.getText();

        if (usuario.equals(usuarioA) & contrasena.equals(contrasenaA)) {
            this.dispose();
            MenuPrincipal menu = new MenuPrincipal();
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ingresaste datos incorrectos, favor ingresalos nuevamente");
        }
    }//GEN-LAST:event_ingresarMouseClicked

    private void jcontrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcontrasenaKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            String usuario = "admin";
            String contrasena = "123456";
            String usuarioA = jusuario.getText();
            String contrasenaA = jcontrasena.getText();
            if (usuario.equals(usuarioA) & contrasena.equals(contrasenaA)) {
                this.dispose();
                MenuPrincipal menu = new MenuPrincipal();
                menu.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Ingresaste datos incorrectos, favor ingresalos nuevamente");
            }
        }
    }//GEN-LAST:event_jcontrasenaKeyPressed

    private void moverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseClicked
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseClicked

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed

    }//GEN-LAST:event_moverMousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        int x = (punto.x - xA);
        int y = (punto.y - yA - 10);
        this.setLocation(x, y);
    }//GEN-LAST:event_moverMouseDragged

    private void cerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseMoved
        cerrar.setBackground(Color.red);
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_cerrarMouseMoved

    private void fondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseMoved
        cerrar.setBackground(new Color(46, 51, 58));
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_fondoMouseMoved

    private void minimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseMoved
        minimizar.setBackground(new Color(32, 178, 170));
        cerrar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_minimizarMouseMoved

    private void moverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseEntered
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseEntered

    private void moverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseExited
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseExited

    private void ColorBarraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorBarraMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_ColorBarraMouseMoved

    private void moverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseMoved

    private void ingresarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseMoved

    }//GEN-LAST:event_ingresarMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorBarra;
    private javax.swing.JLabel Texto;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel contra;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel iconoRe;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jcontrasena;
    private javax.swing.JTextField jusuario;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton mover;
    // End of variables declaration//GEN-END:variables
}
