/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorios
 */
public class SeleccionDeSector extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xA = this.getX();
    int yA = this.getY();

    public static ArrayList<Cliente> clientes = new ArrayList<Cliente>();//se crea el arraylist de los clientes.

    public SeleccionDeSector() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        minimizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        mover = new javax.swing.JButton();
        ColorBarra = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        SectorA1 = new javax.swing.JButton();
        SectorA = new javax.swing.JButton();
        SectorB = new javax.swing.JButton();
        SectorC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        iconoRe1 = new javax.swing.JLabel();
        jTexto1 = new javax.swing.JLabel();
        jTexto2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(450, 200, 50, 50));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setBackground(new java.awt.Color(46, 51, 58));
        minimizar.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("-");
        minimizar.setBorder(null);
        minimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizarMouseMoved(evt);
            }
        });
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, 24));

        cerrar.setBackground(new java.awt.Color(46, 51, 58));
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.setBorder(null);
        cerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cerrarMouseMoved(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 24));

        mover.setBackground(new java.awt.Color(46, 51, 58));
        mover.setBorderPainted(false);
        mover.setContentAreaFilled(false);
        mover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moverMouseMoved(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        getContentPane().add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 24));

        ColorBarra.setBackground(new java.awt.Color(46, 51, 58));
        ColorBarra.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        ColorBarra.setForeground(new java.awt.Color(204, 0, 0));
        ColorBarra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorBarra.setText("Seleccion de Sector");
        ColorBarra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ColorBarra.setOpaque(true);
        ColorBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ColorBarraMouseMoved(evt);
            }
        });
        getContentPane().add(ColorBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 24));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/left-arrow.png"))); // NOI18N
        regresar.setBorderPainted(false);
        regresar.setContentAreaFilled(false);
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 24, 60, 36));

        SectorA1.setBackground(new java.awt.Color(204, 204, 204));
        SectorA1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        SectorA1.setForeground(new java.awt.Color(153, 0, 0));
        SectorA1.setText("Todos los clientes");
        SectorA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SectorA1MouseClicked(evt);
            }
        });
        SectorA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectorA1ActionPerformed(evt);
            }
        });
        getContentPane().add(SectorA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 372, 216, 48));

        SectorA.setBackground(new java.awt.Color(204, 204, 204));
        SectorA.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        SectorA.setForeground(new java.awt.Color(153, 0, 0));
        SectorA.setText("Sector A");
        SectorA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SectorAMouseClicked(evt);
            }
        });
        SectorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectorAActionPerformed(evt);
            }
        });
        getContentPane().add(SectorA, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 156, 192, 48));

        SectorB.setBackground(new java.awt.Color(204, 204, 204));
        SectorB.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        SectorB.setForeground(new java.awt.Color(153, 0, 0));
        SectorB.setText("Sector B");
        SectorB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SectorBMouseClicked(evt);
            }
        });
        SectorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectorBActionPerformed(evt);
            }
        });
        getContentPane().add(SectorB, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 212, 192, 48));

        SectorC.setBackground(new java.awt.Color(204, 204, 204));
        SectorC.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        SectorC.setForeground(new java.awt.Color(153, 0, 0));
        SectorC.setText("Sector C");
        SectorC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SectorCMouseClicked(evt);
            }
        });
        SectorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectorCActionPerformed(evt);
            }
        });
        getContentPane().add(SectorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 285, 192, 48));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        iconoRe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sol4.png"))); // NOI18N
        jPanel1.add(iconoRe1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, 120, 108));

        jTexto1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jTexto1.setText("Ver los clientes");
        getContentPane().add(jTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 108, -1, -1));

        jTexto2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jTexto2.setText("Seleccionar un sector para");
        getContentPane().add(jTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 72, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/red-and-white-bars-hd-wallpaper-7530.jpg"))); // NOI18N
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 51, 58), 3, true));
        fondo.setOpaque(true);
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoMouseMoved(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 468));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
        minimizar.setBackground(new Color(0, 102, 102));

    }//GEN-LAST:event_minimizarMouseClicked

    private void moverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseClicked
        mover.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseClicked

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed

    }//GEN-LAST:event_moverMousePressed

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        Point punto = MouseInfo.getPointerInfo().getLocation();
        int x = (punto.x - xA);
        int y = (punto.y - yA - 10);
        this.setLocation(x, y);
    }//GEN-LAST:event_moverMouseDragged

    private void cerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseMoved
        cerrar.setBackground(Color.red);
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_cerrarMouseMoved

    private void minimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseMoved
        minimizar.setBackground(new Color(32, 178, 170));
        cerrar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_minimizarMouseMoved

    private void moverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseEntered
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseEntered

    private void moverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseExited
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseExited

    private void ColorBarraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorBarraMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_ColorBarraMouseMoved

    private void moverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_moverMouseMoved

    private void fondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseMoved
        cerrar.setBackground(new Color(46, 51, 58));
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_fondoMouseMoved

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        this.dispose();
        ControlClientes control = new ControlClientes();
        control.show();
    }//GEN-LAST:event_regresarMouseClicked

    private void SectorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectorAActionPerformed

    private void SectorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectorBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectorBActionPerformed

    private void SectorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectorCActionPerformed

    private void SectorAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectorAMouseClicked
        this.dispose();
        SectorA ventana = new SectorA();
        ventana.setVisible(true);
    }//GEN-LAST:event_SectorAMouseClicked

    private void SectorBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectorBMouseClicked
        this.dispose();
        SectorB ventana = new SectorB();
        ventana.setVisible(true);
    }//GEN-LAST:event_SectorBMouseClicked

    private void SectorCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectorCMouseClicked
        this.dispose();
        SectorC ventana = new SectorC();
        ventana.setVisible(true);
    }//GEN-LAST:event_SectorCMouseClicked

    private void SectorA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectorA1MouseClicked
        this.dispose();
        SectorTodos ventana = new SectorTodos();
        ventana.show();
    }//GEN-LAST:event_SectorA1MouseClicked

    private void SectorA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectorA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectorA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionDeSector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionDeSector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorBarra;
    private javax.swing.JButton SectorA;
    private javax.swing.JButton SectorA1;
    private javax.swing.JButton SectorB;
    private javax.swing.JButton SectorC;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconoRe1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTexto1;
    private javax.swing.JLabel jTexto2;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton mover;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
