/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial;

import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Farat
 */
public class Vigilancia extends javax.swing.JFrame {

    public Vigilancia() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        btn_atras = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        txt_diaA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_area = new javax.swing.JTextArea();
        txt_horaA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_anoA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Vehiculo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eraser.png"))); // NOI18N
        btn_limpiar.setBorderPainted(false);
        btn_limpiar.setContentAreaFilled(false);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 80, 50));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 108, 79, -1));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 140, 79, -1));

        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow - copia.png"))); // NOI18N
        btn_atras.setBorderPainted(false);
        btn_atras.setContentAreaFilled(false);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (4).png"))); // NOI18N
        btn_agregar.setBorderPainted(false);
        btn_agregar.setContentAreaFilled(false);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 312, 80, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Placa:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Dia :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 224, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dueño");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, 20));
        getContentPane().add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 108, 73, -1));
        getContentPane().add(txt_diaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 79, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Apellido:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Hora:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 264, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Año:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 264, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 108, -1, -1));

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thin-printer-.png"))); // NOI18N
        btn_mostrar.setBorderPainted(false);
        btn_mostrar.setContentAreaFilled(false);
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 48, 70, 50));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar (2).png"))); // NOI18N
        btn_eliminar.setBorderPainted(false);
        btn_eliminar.setContentAreaFilled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 384, 70, 50));

        txt_area.setEditable(false);
        txt_area.setColumns(20);
        txt_area.setRows(5);
        getContentPane().add(txt_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 110, 204, 252));
        getContentPane().add(txt_horaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 79, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Eliminar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 432, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Mostrar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 36, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Guardar");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Borrar");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));
        getContentPane().add(txt_anoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 260, 80, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red-and-white-bars-hd-wallpaper-7530.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, 800, 590));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 1030, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed

        try {
            FileInputStream Datos = new FileInputStream("Vigilancia.txt");
            DataInputStream Entrada = new DataInputStream(Datos);
            BufferedReader br = new BufferedReader(new InputStreamReader(Entrada));
            String Lineas;
            while ((Lineas = br.readLine()) != null) {
                txt_area.append(Lineas + "\n");

            }
            Entrada.close();
        } catch (IOException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error al abrir archivo  ");
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            FileWriter Escribir = new FileWriter("Vigilancia.txt");
            String Texto = txt_area.getText();
            PrintWriter Imprime = new PrintWriter(Escribir);
            Imprime.print(Texto);
            Escribir.close();
            JOptionPane.showMessageDialog(null, "Texto guardado  ");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al abrir archivo  " + e);
        }


    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed

        txt_nombre.setText(null); // limpiar el textfield
        txt_apellido.setText(null); // limpiar el textfield
        txt_anoA.setText(null); // limpiar el textfield
        txt_diaA.setText(null); // limpiar el textfield
        txt_horaA.setText(null); // limpiar el textfield
        txt_placa.setText(null); // limpiar el textfield

    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        try {

            File f = new File("Vigilancia.txt");
            FileWriter fw = null;
            try {
                fw = new FileWriter(f, false);
            } catch (IOException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            fw.write("");
            fw.close();

        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "\n El Archivo se eliminó exitosamente! \n");


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed

        this.dispose();
        Empleados in = new Empleados();
        in.show();

    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed

        try {
            if (!(txt_nombre.getText().equals("") && txt_apellido.getText().equals("") && txt_diaA.getText().equals("") 
                    && txt_anoA.getText().equals("") && txt_horaA.getText().equals("") && txt_placa.getText().equals(""))) {

                File archivo = new File("./Vigilancia.txt");
                if (!archivo.exists()) {
                    archivo.createNewFile();
                }

                FileWriter fw = new FileWriter(archivo.getAbsoluteFile());
                BufferedWriter bw = new BufferedWriter(fw);
                String imprimir = "Personas\nNombre: ";
                imprimir += txt_nombre.getText() + "\nApellido de Persona: ";
                imprimir += txt_apellido.getText() + "\nDia de Persona: ";
                imprimir += txt_diaA.getText() + "\nHora de Persona: ";
                imprimir += txt_horaA.getText() + "\nAño de Persona: ";
                imprimir += txt_anoA.getText() + "\nPlaca de Vehiculo: ";
                imprimir += txt_placa.getText() + "\nDia  Vehiculo: ";
                imprimir += "---";
                bw.write(imprimir);
                bw.close();

                txt_nombre.setText(null);
                txt_apellido.setText(null);
                txt_diaA.setText(null);
                txt_horaA.setText(null);
                txt_anoA.setText(null);
                txt_placa.setText(null);

            } else { 
                JOptionPane.showMessageDialog(null, "Falto informacion");
            }

            JOptionPane.showMessageDialog(null, "\nLos datos han sido agregados exitosamente\n");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Archivo no encontrado.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Hubo un problema al leer el Archivo.");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Hubo un error en los datos, favor\nverificar que todos esten\ncorrectamente ingresados");

        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vigilancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vigilancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vigilancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vigilancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vigilancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_anoA;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_diaA;
    private javax.swing.JTextField txt_horaA;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables
}
